name: Android APK (Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk libffi-dev libssl-dev libbz2-dev libsqlite3-dev libncurses5-dev libncursesw5-dev libreadline-dev zlib1g-dev liblzma-dev

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/licenses/android-sdk-license-2
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/licenses/android-sdk-preview-license
          echo "84831b9409656b91842a0d1ff3699a997c9c1d12" > ~/.android/licenses/android-sdk-license-3
          echo "d975f751698a77b662f1254ddbeed3901e976f5a" > ~/.android/licenses/android-sdk-license-4
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/licenses/android-sdk-preview-license-2

      - name: Cache buildozer dirs
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython

      - name: Install Android SDK and build-tools
        run: |
          # Download Android SDK command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          
          # Set environment variables
          export ANDROID_HOME=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          
          # Accept licenses and install required packages
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;35.0.1" "platforms;android-35"
          
          # Create symlink for buildozer to find our SDK
          mkdir -p ~/.buildozer/android/platform
          ln -sf $PWD/android-sdk ~/.buildozer/android/platform/android-sdk
          
          # Set environment for buildozer
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

      - name: Build APK
        run: |
          # Force buildozer to use our pre-installed SDK
          export ANDROID_HOME=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          
          # Verify aidl is available
          echo "Checking for aidl..."
          find $ANDROID_HOME -name "aidl" -type f
          
          # Build with verbose output
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: bin/*.apk


